/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ReachRouteImport } from './routes/reach'
import { Route as PushTestRouteImport } from './routes/push-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConfessHereRouteImport } from './routes/confess-here'
import { Route as IndexRouteImport } from './routes/index'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const PushTestRoute = PushTestRouteImport.update({
  id: '/push-test',
  path: '/push-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessHereRoute = ConfessHereRouteImport.update({
  id: '/confess-here',
  path: '/confess-here',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confess-here': typeof ConfessHereRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/push-test': typeof PushTestRoute
  '/reach': typeof ReachRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confess-here': typeof ConfessHereRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/push-test': typeof PushTestRoute
  '/reach': typeof ReachRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confess-here': typeof ConfessHereRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/push-test': typeof PushTestRoute
  '/reach': typeof ReachRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confess-here'
    | '/events'
    | '/home'
    | '/login'
    | '/push-test'
    | '/reach'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confess-here'
    | '/events'
    | '/home'
    | '/login'
    | '/push-test'
    | '/reach'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/confess-here'
    | '/events'
    | '/home'
    | '/login'
    | '/push-test'
    | '/reach'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfessHereRoute: typeof ConfessHereRoute
  EventsRoute: typeof EventsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PushTestRoute: typeof PushTestRoute
  ReachRoute: typeof ReachRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push-test': {
      id: '/push-test'
      path: '/push-test'
      fullPath: '/push-test'
      preLoaderRoute: typeof PushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confess-here': {
      id: '/confess-here'
      path: '/confess-here'
      fullPath: '/confess-here'
      preLoaderRoute: typeof ConfessHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfessHereRoute: ConfessHereRoute,
  EventsRoute: EventsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PushTestRoute: PushTestRoute,
  ReachRoute: ReachRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
